name: Aggressive Cleanup

runs:
  using: composite
  steps:
    - name: Free disk space
      shell: bash
      run: |
        sudo swapoff -a || true
        sudo rm -f /swapfile
        sudo rm -rf \
          /usr/lib/jvm \
          /usr/lib/mono \
          /usr/lib/google-cloud-sdk \
          /usr/local/.ghcup \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift \
          /opt/az \
          /opt/google \
          /opt/microsoft \
          /opt/hostedtoolcache

        docker system prune -af || true
        docker builder prune -af || true
        sudo apt-get clean || true

        df -h